Golang Homework 7.3 - Get/Post
stevenstr/go_hw pull request #17
Opened 2019-12-11 13:18 UTC by stevenstr

**Home work 7.3 - Task:**
●Web server, responds to “/” (404 on any other request)
●Support POST and GET methods
• On GET request returns HTML page, containing FORM with name and address fields + submit button.
Also there is a placeholder to display token on this page.
● On POST request reads name+address from body and creates a token as “name:address”.
Then saves this token to Cookies
●Page reloads, token value displayed on page

2019-12-11 13:34 UTC, burov requested changes
Please use switch in handleMainPage

2019-12-11 13:34 UTC, burov commented on main.go
> +	if r.Method == http.MethodGet {
switch could improve code readability

2019-12-11 13:39 UTC, stevenstr commented on main.go
> +	if r.Method == http.MethodGet {
Great thenks.done it)

2019-12-16 10:35 UTC, wshaman approved these changes

2019-12-16 10:35 UTC, wshaman commented on main.go
> +		w.Write(formNameAddrTmpl)
It should be writing html OR redirecting.
This code will work, but could make crazy some browsers.

2019-12-16 15:23 UTC, burov approved these changes
Overall looks ok for me

2019-12-16 15:23 UTC, burov commented on main.go
> +		return
return redundant because by default switches don't use ```fall trough``` behaviour

2019-12-16 18:18 UTC, closed without merging